[package]
name = "toql_rocket"
version = "0.3.0"
authors = ["Artos <roy.ganz@glanis.biz>"]
edition = "2018"
description = "Rocket integration for toql"
keywords = ["toql", "rocket"]
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/roy-ganz/toql_rocket"

[dependencies]
toql = { version = "0.3", git="https://github.com/roy-ganz/toql.git", branch="v0.3" }
toql_mysql = { version = "0.3", git="https://github.com/roy-ganz/toql_mysql.git", branch="v0.3", optional= true }

rocket = "0.4"
log = "0.4"

[features]
mysql = [ "toql_mysql"]


[dev-dependencies]
rocket = "0.4" 
rocket_contrib =  {version = "0.4", default-features = false, features = ["mysql_pool", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[[example]]
name = "crud_mysql"
path = "examples/crud_mysql/main.rs"
required-features = ["mysql14"]



 
