[package]
name = "toql_rocket"
version = "0.1.2"
authors = ["Artos <roy.ganz@glanis.biz>"]
edition = "2018"
description = "Rocket integration for toql"
keywords = ["toql"]
readme = "../README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/roy-ganz/toql"

[dependencies]
toql = { version = "0.1", path = "../toql" }
rocket = "0.4"
log = "0.4"

[features]
mysql = [ "toql/mysql"]


[dev-dependencies]
rocket = "0.4" 
rocket_contrib =  {version = "0.4", default-features = false, features = ["mysql_pool", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
#toql = { version = "0.1", path = "../toql", features= ["mysql"] }

[[example]]
name = "crud_mysql"
path = "examples/crud_mysql/main.rs"
required-features = ["mysql"]

 
