[package]
name = "toql_rocket"
version = "0.1.5"
authors = ["Artos <roy.ganz@glanis.biz>"]
edition = "2018"
description = "Rocket integration for toql"
keywords = ["toql", "rocket"]
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/roy-ganz/toql_rocket"

[dependencies]
toql = { version = "0.1", path = "../toql" }
#rocket = "0.4.2"
#rocket = { git ="https://github.com/SergioBenitez/Rocket.git"}
rocket = {path ="../Rocket/core/lib"}
log = "0.4"

[features]
mysql = [ "toql/mysql"]


[dev-dependencies]
rocket = { path ="../Rocket/core/lib"}

#rocket = "0.4.2" 
#rocket_contrib =  {version = "0.4.2", default-features = false, features = ["mysql_pool", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[example]]
name = "crud_mysql"
path = "examples/crud_mysql/main.rs"
required-features = ["mysql"]

 
